09:34:07,663 [WARNING] PyNaCl is not installed, voice will NOT be  client.py:320
             supported                                                          
09:34:07,667 [INFO] Loading pyproject.toml to parse version.           bot.py:44
09:34:07,668 [INFO] Bot version: 1.2.3                                 bot.py:47
09:34:07,942 [INFO] Using SQLite version 3.37.2.               scheduler.py:1320
09:34:07,948 [INFO] Loading scheduler cog.                     scheduler.py:1159
09:34:07,951 [INFO] Populated 0 schedules.                     scheduler.py:1177
09:34:07,953 [INFO] Starting bot.                        start_discord_bot.py:60
09:34:07,954 [INFO] logging in using static token                  client.py:628
09:34:08,282 [INFO] Slash commands sync skipped.                       bot.py:83
09:34:08,438 [INFO] Shard ID None has sent the IDENTIFY payload.  gateway.py:458
09:34:08,651 [INFO] Shard ID None has connected to Gateway        gateway.py:546
             (Session ID: 63509872f535e800abe2e837f2ca1c23).                    
09:34:10,659 [INFO] Bot is ready.                                      bot.py:90
09:36:36,361 [WARNING] PyNaCl is not installed, voice will NOT be  client.py:320
             supported                                                          
09:36:36,364 [INFO] Loading pyproject.toml to parse version.           bot.py:44
09:36:36,366 [INFO] Bot version: 1.2.3                                 bot.py:47
09:36:36,641 [INFO] Using SQLite version 3.37.2.               scheduler.py:1320
09:36:36,647 [INFO] Loading scheduler cog.                     scheduler.py:1159
09:36:36,649 [INFO] Populated 0 schedules.                     scheduler.py:1177
09:36:36,653 [INFO] Starting bot.                        start_discord_bot.py:60
09:36:36,654 [INFO] logging in using static token                  client.py:628
09:36:37,287 [INFO] Slash commands sync skipped.                       bot.py:83
09:36:37,444 [INFO] Shard ID None has sent the IDENTIFY payload.  gateway.py:458
09:36:37,627 [INFO] Shard ID None has connected to Gateway        gateway.py:546
             (Session ID: 165288d2a22628176a753599826bae36).                    
09:36:39,638 [INFO] Bot is ready.                                      bot.py:90
09:37:44,760 [WARNING] PyNaCl is not installed, voice will NOT be  client.py:320
             supported                                                          
09:37:44,763 [INFO] Loading pyproject.toml to parse version.           bot.py:44
09:37:44,765 [INFO] Bot version: 1.2.3                                 bot.py:47
09:37:45,040 [INFO] Using SQLite version 3.37.2.               scheduler.py:1320
09:37:45,046 [INFO] Loading scheduler cog.                     scheduler.py:1159
09:37:45,048 [INFO] Populated 0 schedules.                     scheduler.py:1177
09:37:45,052 [INFO] Starting bot.                        start_discord_bot.py:60
09:37:45,053 [INFO] logging in using static token                  client.py:628
09:37:45,486 [INFO] Slash commands sync skipped.                       bot.py:83
09:37:45,649 [INFO] Shard ID None has sent the IDENTIFY payload.  gateway.py:458
09:37:45,836 [INFO] Shard ID None has connected to Gateway        gateway.py:546
             (Session ID: 10829e024420041e756e518c6ee79d5e).                    
09:37:47,845 [INFO] Bot is ready.                                      bot.py:90
09:39:46,917 [ERROR] Task exception was never retrieved            runners.py:44
             future: <Task finished                                             
             name='discord-ui-view-timeout-8d3b0ed47151ea8aa9f0385              
             b3f1bfb16'                                                         
             coro=<General.show_tasks.<locals>.MyView.on_timeout()              
             done, defined at                                                   
             /home/leon/Desktop/discord_bot/cogs/general.py:89>                 
             exception=AttributeError("'MyView' object has no                   
             attribute 'message'")>                                             
             ╭──────── Traceback (most recent call last) ────────╮              
             │ /home/leon/Desktop/discord_bot/cogs/general.py:90 │              
             │ in on_timeout                                     │              
             │                                                   │              
             │    87 │   │                                       │              
             │    88 │   │   # guild = self.bot.get_guild(event. │              
             │    89 │   │                                       │              
             │ ❱  90 │   │   class MyView(discord.ui.View):      │              
             │    91 │   │   │   async def on_timeout(self):     │              
             │    92 │   │   │   │   await self.message.edit(con │              
             │    93                                             │              
             │                                                   │              
             │ ╭───────────────── locals ──────────────────╮     │              
             │ │ self = <MyView timeout=180.0 children=21> │     │              
             │ ╰───────────────────────────────────────────╯     │              
             ╰───────────────────────────────────────────────────╯              
             AttributeError: 'MyView' object has no attribute                   
             'message'                                                          
09:41:16,963 [ERROR] Task exception was never retrieved            runners.py:44
             future: <Task finished                                             
             name='discord-ui-view-timeout-f21fe68c68dbfaa54725eeb              
             49c2344e0'                                                         
             coro=<General.show_tasks.<locals>.MyView.on_timeout()              
             done, defined at                                                   
             /home/leon/Desktop/discord_bot/cogs/general.py:89>                 
             exception=AttributeError("'MyView' object has no                   
             attribute 'message'")>                                             
             ╭──────── Traceback (most recent call last) ────────╮              
             │ /home/leon/Desktop/discord_bot/cogs/general.py:90 │              
             │ in on_timeout                                     │              
             │                                                   │              
             │    87 │   │                                       │              
             │    88 │   │   # guild = self.bot.get_guild(event. │              
             │    89 │   │                                       │              
             │ ❱  90 │   │   class MyView(discord.ui.View):      │              
             │    91 │   │   │   async def on_timeout(self):     │              
             │    92 │   │   │   │   await self.message.edit(con │              
             │    93                                             │              
             │                                                   │              
             │ ╭───────────────── locals ──────────────────╮     │              
             │ │ self = <MyView timeout=180.0 children=22> │     │              
             │ ╰───────────────────────────────────────────╯     │              
             ╰───────────────────────────────────────────────────╯              
             AttributeError: 'MyView' object has no attribute                   
             'message'                                                          
09:41:17,241 [ERROR] Task exception was never retrieved            runners.py:44
             future: <Task finished                                             
             name='discord-ui-view-timeout-bf593941f9c9fb9dba65b8b              
             0b91971e4'                                                         
             coro=<General.show_tasks.<locals>.MyView.on_timeout()              
             done, defined at                                                   
             /home/leon/Desktop/discord_bot/cogs/general.py:91>                 
             exception=AttributeError("'MyView' object has no                   
             attribute 'message'")>                                             
             ╭──────── Traceback (most recent call last) ────────╮              
             │ /home/leon/Desktop/discord_bot/cogs/general.py:92 │              
             │ in on_timeout                                     │              
             │                                                   │              
             │    89 │   │                                       │              
             │    90 │   │   class MyView(discord.ui.View):      │              
             │    91 │   │   │   async def on_timeout(self):     │              
             │ ❱  92 │   │   │   │   await self.message.edit(con │              
             │    93 │   │   │                                   │              
             │    94 │   │   │   def __init__(self, buttons_data │              
             │    95 │   │   │   │   super().__init__()          │              
             │                                                   │              
             │ ╭───────────────── locals ──────────────────╮     │              
             │ │ self = <MyView timeout=180.0 children=22> │     │              
             │ ╰───────────────────────────────────────────╯     │              
             ╰───────────────────────────────────────────────────╯              
             AttributeError: 'MyView' object has no attribute                   
             'message'                                                          
